### ISSUE TITLE
Runtime error when accessing API URL

### ISSUE THREAD

**Issue by adrenalinmike** [a1g3/dns-scanner#1]
After compiling the code as described and starting the HTTP server, I get a runtime error whenever I access the API
http://myip:10000/api/fqd.dns 

2023/10/10 16:22:48 http: panic serving server_ip:53029: runtime error: invalid memory address or nil pointer dereference
goroutine 5 [running]:
net/http.(*conn).serve.func1()
	/usr/lib/go/src/net/http/server.go:1854 +0xbf
panic({0x724760, 0x9ec190})
	/usr/lib/go/src/runtime/panic.go:890 +0x263
dnsScanner/workers.ScanDns({0xc000094009, 0x7})
	/root/source/go/dns-scanner/workers/dnsScanner.go:45 +0x30d
main.scanDns({0x807b50, 0xc0000ae000}, 0xc00008c1e0?)
	/root/source/go/dns-scanner/main.go:18 +0x85
net/http.HandlerFunc.ServeHTTP(0xc000092300?, {0x807b50?, 0xc0000ae000?}, 0x800?)
	/usr/lib/go/src/net/http/server.go:2122 +0x2f
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000000180, {0x807b50, 0xc0000ae000}, 0xc000092000)
	/root/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
net/http.serverHandler.ServeHTTP({0xc00008c030?}, {0x807b50, 0xc0000ae000}, 0xc000092000)
	/usr/lib/go/src/net/http/server.go:2936 +0x316
net/http.(*conn).serve(0xc000164090, {0x807d78, 0xc000150c90})
	/usr/lib/go/src/net/http/server.go:1995 +0x612
created by net/http.(*Server).Serve
	/usr/lib/go/src/net/http/server.go:3089 +0x5ed

**Comment by a1g3** [comment]
Hi!

Sorry for the delay.  I've been attending a couple conferences over the past month.  This error is due to the dns library not being able to find the config file.  Make sure you set the `DNSSCAN_RESOLV_PATH` environmental variable to the path of the `resolv.conf` file. This file contains the information needed for the DNS library to perform lookups. There is a example file in the root of this repository that uses 8.8.8.8 to resolve DNS queries.
